fix: update spectral (#40)
* fix: [RDB-134] update status swagger

* fix: [RDB-134] update status swagger

* fix: rename spectral file

* fix: spectral file

* fix: spectral file

* fix: spectral file

* fix: revert onboarding appIo

diff --git a/.github/workflows/IDPAY-spectral-check.yml b/.github/workflows/IDPAY-spectral-check.yml
--- a/.github/workflows/IDPAY-spectral-check.yml
+++ b/.github/workflows/IDPAY-spectral-check.yml
@@ -59,13 +59,10 @@ jobs:
             echo "🔎 Validating $file"
             echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
 
-            # Run Spectral and display full results
-            spectral lint -r node_modules/@stoplight/spectral-owasp-ruleset/dist/ruleset.mjs "$file"
-            if [ $? -ne 0 ]; then
+            spectral lint -r .spectral.yaml --verbose "$file" || {
+              echo "❌ Spectral validation failed for $file"
               failed=1
-            else
-              echo "✅ $file: Passed validation."
-            fi
+            }
           done
 
           if [ $failed -eq 1 ]; then
